import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/AI/Agent/OpenClaw": "structure",
  "/BackEnd/Java/JVM": "structure",
  "/BackEnd/Java/Concurrent": "structure",
  "/BackEnd/Lua/LuaBase": "structure",
  "/BackEnd/Common/GRPC": "structure",
  "/FrontEnd/Framework/Vue2": "structure",
  "/FrontEnd/Engineering/PackageManager": "structure",
  "/DevOps/Cloud/Container": "structure",
  "/DevOps/Cloud/Kubernetes": "structure",
  "/Base/DataStructure": "structure",
  "/Base/Algorithm": "structure",
  "/Base/Network/": "structure",
  "/Development/DevTools/IntellijIdea": "structure",
  "/Development/DevTools/VSCode": "structure",
  "/DevOps/Windows/Bat/": "structure",
  "/DevOps/Linux/Base/": "structure",
  "/DevOps/Linux/Bash/": "structure",
  "/DevOps/Linux/Ansible/": "structure",
  "/DevOps/Linux/BindDNS/": "structure",
  "/DevOps/Linux/SSH/": "structure",
  "/DevOps/Middleware/MySQL/": "structure",
});
